/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "rpsplayerrecord-rpsdev",
            "region": "us-east-1"
        },
        {
            "tableName": "userrecord-rpsdev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:426c1bda-24ca-4307-8574-acd8fcd713d1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_txuSaRM16",
    "aws_user_pools_web_client_id": "s0pgdvs9s3jtkfb0cliihv1r3",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "rpsapi",
            "endpoint": "https://j5xaba3tpl.execute-api.us-east-1.amazonaws.com/rpsdev",
            "region": "us-east-1"
        },
        {
            "name": "apie20fbc10",
            "endpoint": "https://dj3vofs1tk.execute-api.us-east-1.amazonaws.com/rpsdev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
